# Generated by Django 4.2.7 on 2023-11-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/banner_imgs')),
                ('banner_title1', models.CharField(max_length=100)),
                ('banner_title2', models.CharField(max_length=100)),
                ('Discount_Deal', models.CharField(max_length=100)),
            ],
        ),
    ]
